### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by oliwynn** [ChrisPhillips-cminion/APIConnect-ImpactAnalysis#4] opened 2017-03-29 12:54 UTC
Running this against my bluemix account I get the following:

`✔ Logging in...
✔ Fetching organizations
? Please select the target organization: oliukibmcom-api-economy-demo-dev
✔ Fetching catalogs for organization: oliukibmcom-api-economy-demo-dev
? Please select the target catalog: sb
✔ Get DisplayName for Catalog : sb
? Please select which data you wish to show: (Press <space> to select, <a> to toggle all, <i> to inverse se
lection, <left> to move entry up, <right> to move entry down)Service - Host / QueueManager, Service - Conte
xtRoute / Queue, API, Product, Plan, Application
? Do you want to save this config: Yes
? Where do you want the config file to be saved apic-dev-sandbox.json
Config saved to apic-dev-sandbox.json
Begin downloadYamlForProduct function for sb
✔ Downloading Product sb:harrogatebc:1.0.0 this may take a few minutes...
✔ Downloading Product sb:salesforce:1.0.0 this may take a few minutes...
✔ Downloading Product sb:hbc-properties:1.0.0 this may take a few minutes...
✔ Downloading Product sb:customers:1.0.0 this may take a few minutes...
✔ Downloading Product sb:testapi:1.0.0 this may take a few minutes...
✔ Downloading Product sb:products:1.0.0 this may take a few minutes...
✔ Downloading Product sb:think:1.0.0 this may take a few minutes...
https://apiconnect-d4c82f39-38df-4b85-9fe9-7988fc0bd2a5.oliukibmcom-api-economy-demo-dev.apic.eu-gb.mybluemix.net$(request.path)$(request.search)
https://thinkibm-services.mybluemix.net/financing/calculate
https://apiconnect-b77e772e-c350-46d0-a725-d2f2c7dd6509.oliukibmcom-api-economy-demo-dev.apic.eu-gb.mybluemix.net$(request.path)$(request.search)
https://apiconnect-d43717ae-0ccf-4a1e-89fd-c5e29e1c895a.oliukibmcom-api-economy-demo-dev.apic.eu-gb.mybluemix.net$(request.path)$(request.search)
https://apiconnect-1077bca7-fd19-40bd-93db-093ae4e5d23a.oliukibmcom-api-economy-demo-dev.apic.eu-gb.mybluemix.net$(request.path)$(request.search)
http://$(target-url)$(request.path)
https://apiconnect-54bc9244-2091-4714-97cf-fbd411a326a7.oliukibmcom-api-economy-demo-dev.apic.eu-gb.mybluemix.net$(request.path)$(request.search)
Processing Complete for sb
/Users/oliverwynn/apic/APIConnect-ImpactAnalysis/lib/processDir.js:103
                                if (plan.apps.length === 0) {
                                             ^

TypeError: Cannot read property 'length' of undefined
    at /Users/oliverwynn/apic/APIConnect-ImpactAnalysis/lib/processDir.js:103:46
    at /Users/oliverwynn/apic/APIConnect-ImpactAnalysis/node_modules/foreachthen/index.js:9:13
    at /Users/oliverwynn/apic/APIConnect-ImpactAnalysis/node_modules/foreachthen/node_modules/async/dist/async.js:3686:9
    at eachOfArrayLike (/Users/oliverwynn/apic/APIConnect-ImpactAnalysis/node_modules/foreachthen/node_modules/async/dist/async.js:941:9)
    at eachOf (/Users/oliverwynn/apic/APIConnect-ImpactAnalysis/node_modules/foreachthen/node_modules/async/dist/async.js:991:5)
    at _parallel (/Users/oliverwynn/apic/APIConnect-ImpactAnalysis/node_modules/foreachthen/node_modules/async/dist/async.js:3685:5)
    at Object.parallelLimit [as parallel] (/Users/oliverwynn/apic/APIConnect-ImpactAnalysis/node_modules/foreachthen/node_modules/async/dist/async.js:3765:3)
    at Array.forEachThen (/Users/oliverwynn/apic/APIConnect-ImpactAnalysis/node_modules/foreachthen/index.js:12:11)
    at /Users/oliverwynn/apic/APIConnect-ImpactAnalysis/lib/processDir.js:102:41
    at `/Users/oliverwynn/apic/APIConnect-ImpactAnalysis/node_modules/foreachthen/index.js:9:13``

**Comment by ChrisPhillips-cminion** [comment] 2017-03-29 23:04
Can you please provide the product and API yaml as I cannot reproduce this.

**Comment by ChrisPhillips-cminion** [comment] 2017-04-05 07:58
Closing until it can be reproduced. Oli when you are back feel free to send me the swagger and i will reopen it

**Closed** 2017-04-05 07:58 UTC
