### ISSUE TITLE
Issue with executing apicia.js

### ISSUE THREAD

**Issue by jinglerobs** [ChrisPhillips-cminion/APIConnect-ImpactAnalysis#5] opened 2017-03-30 05:41 UTC
Getting below error while executing apicia.js

====================================
_D:\APICwork\APIConnect-ImpactAnalysis>npm -version
4.4.4

D:\APICwork\APIConnect-ImpactAnalysis>node apicia.js
? API Connect Management Server?

D:\APICwork\APIConnect-ImpactAnalysis\lib\handleUserInput.js:300
        inquirer.prompt(questions).then(function (answers) {
                                   ^

TypeError: inquirer.prompt(...).then is not a function
    at handleUserInput (D:\APICwork\APIConnect-ImpactAnalysis\lib\handleUserInpu
t.js:300:36)
    at Object.<anonymous> (D:\APICwork\APIConnect-ImpactAnalysis\apicia.js:22:5)

    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3_
=========================================================

**Comment by ChrisPhillips-cminion** [comment] 2017-03-30 07:51
Are you running the latest version of the code? This is caused by a dependency issue and was updated in the latest packages.json.  

Please can you confirm your packages.json matches contains this line  "inquirer": "^3.0.6",

**Comment by ChrisPhillips-cminion** [comment] 2017-04-02 22:02
Hi, are you still hitting this issue?

**Comment by ChrisPhillips-cminion** [comment] 2017-04-06 10:40
Closing this issue

**Closed by ChrisPhillips-cminion** 2017-04-06 10:40 UTC
